version: '3'
services:
  lida:
    image: mastrogeppetto/matilda_nodb:latest
    volumes: 
      - ./matilda_conf:/app/matilda_conf
    network_mode: "host"
    restart: always
    logging:
      driver: "json-file"
  nginx:
    image: nginx
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"
