version: '3'
services:
  lida:
    image: mastrogeppetto/dockerlida:latest
    ports: 
      - "5000:5000"
    network_mode: "host"
  mongodb:
    image: mongo:bionic
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./configdb:/data/configdb
      - ./db:/data/db
    network_mode: "host"
  nginx:
    image: nginx
    ports: 
      - "443:443"
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
    network_mode: "host"

