version: '3'
services:
  watchtower:
    image: containrrr/watchtower
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 600
  lida:
    image: davivcu/matilda:multimodel
    volumes: 
      - ./configuration:/configuration
    network_mode: "host"
    restart: always
    logging:
      driver: "json-file"
  mongodb:
    image: mongo:bionic
    volumes:
      - ./configdb:/data/configdb
      - ./db:/data/db
    network_mode: "host"
    restart: always
    logging:
      driver: "json-file"
  nginx:
    image: nginx
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"
